spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  sql:
    init:
      mode: always
logging:
  level:
    org:
    springframework:
      transaction:
        interceptor: trace
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
