DROP TABLE IF EXISTS TWIT;
DROP TABLE IF EXISTS MEMBERS;

CREATE TABLE MEMBERS
(
    MEMBER_ID BIGINT AUTO_INCREMENT,
    EMAIL     VARCHAR(255),
    PASSWORD  VARCHAR(255),
    CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE TWIT
(
    TWIT_ID   BIGINT AUTO_INCREMENT,
    CONTENT   TEXT,
    MEMBER_ID BIGINT,
    VERSION   BIGINT DEFAULT 1,
    CONSTRAINT TWIT_PK PRIMARY KEY (TWIT_ID),
    CONSTRAINT TWIT_FK_01 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS (MEMBER_ID)
);