DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_ID BIGINT AUTO_INCREMENT,
    EMAIL     VARCHAR(255),
    PASSWORD  VARCHAR(255),
    CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
);

INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('user@naver.com', 'user1234');