CREATE TABLE MEMBER
(
    MEMBER_ID  BIGINT AUTO_INCREMENT,
    EMAIL    VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (MEMBER_ID),
    CONSTRAINT USER_UK_01 UNIQUE (EMAIL)
);