DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_ID  BIGINT AUTO_INCREMENT,
    EMAIL    VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (MEMBER_ID)
);

INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('user1234@naver.com', 'user1234');